#!/usr/bin/env python3
"""Host-mediated barrier across HBM-PIM units: config generation, runs and the sweep collector (DAMOV).

  run.py --participants 16                       # one run
  run.py --sweep 1,4,8,16 --jobs 4               # scalability sweep (one HBM3E stack = 16 channels = 16 PIM units)
  run.py --sweep 16 --phases 100,1000,10000      # phase-length sensitivity
  run.py --collect                               # rebuild summary.csv from finished runs

Core 0 is the host (full hierarchy, host PHY path); cores 1..N are the PIM units, one per HBM3E channel
(sys.cores.pim.pim = true -> Request::Flag::PIM -> base-die hops instead of the PHY). The last-level cache is
bypassed, as in DAMOV's PIM template, so the host and the PIM units are not coherent with each other; the mailbox
lines are registered uncached by the app, so every flag access really goes to DRAM.
"""
import argparse
import csv
import itertools
import os
import pathlib
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor

HERE = pathlib.Path(__file__).resolve().parent
SIM = HERE.parent                      # DAMOV/simulator
ROOT = SIM.parent.parent               # pnm-repos
IMAGE = "zsim-bionic-r2"
APP = "../workloads/sync-primitives/barrier_host"

CFG = """// Generated by barrier/run.py -- host-mediated barrier across HBM-PIM units.
sys = {{
    lineSize = 64;
    frequency = {mhz};

    cores = {{
        host = {{                 // core 0: the mediator, normal cache hierarchy, host PHY path
            type = "OOO";
            cores = 1;
            icache = "l1i_host";
            dcache = "l1d_host";
            pim = false;
        }};
        pim = {{                  // cores 1..N: one PIM unit per HBM3E channel
            type = "OOO";
            cores = {participants};
            icache = "l1i_pim";
            dcache = "l1d_pim";
            pim = true;
        }};
    }};

    caches = {{
        l1d_host = {{ caches = 1; size = 32768; latency = 4; array = {{ type = "SetAssoc"; ways = 8; }}; }};
        l1i_host = {{ caches = 1; size = 32768; latency = 3; array = {{ type = "SetAssoc"; ways = 4; }}; }};
        l2_host  = {{ caches = 1; size = 262144; latency = 7; array = {{ type = "SetAssoc"; ways = 8; }};
                     children = "l1i_host|l1d_host"; }};

        l1d_pim = {{ caches = {participants}; size = 32768; latency = 4; array = {{ type = "SetAssoc"; ways = 8; }}; }};
        l1i_pim = {{ caches = {participants}; size = 32768; latency = 3; array = {{ type = "SetAssoc"; ways = 4; }}; }};

        l3 = {{                   // bypassed (DAMOV's PIM model): no LLC data, and no coherence host <-> PIM
            caches = 1;
            banks = 4;
            size = 8388608;
            latency = 27;
            array = {{ type = "SetAssoc"; hash = "H3"; ways = 16; }};
            bypass = true;
            children = "l2_host l1i_pim|l1d_pim";
        }};
    }};

    mem = {{
        type = "Ramulator2";
        clockMode = "ns";
        ramulatorConfig = "{mem}";
        latency = 1;
    }};
}};

sim = {{
    pimMode = false;          // per-core: sys.cores.<group>.pim
    stats = "{stats}";
    phaseLength = {phase};
    statsPhaseInterval = 10000;
    printHierarchy = true;
    gmMBytes = 8192;
    pinOptions = "-ifeellucky";
    deadlockDetection = false;
}};

process0 = {{
    command = "{cmd}";
    startFastForwarded = True;
}};
"""


def name_of(a, n, phase):
    tag = f"hbm3e__n{n}__p{phase}__f{int(a.mhz)}"
    return tag if a.stacks == 1 else tag + f"__s{a.stacks}"


def mem_of(a):
    if a.mem:
        return a.mem
    return ("ramulator2-configs/HBM3E-24Gb_12hi.yaml" if a.stacks == 1
            else f"ramulator2-configs/HBM3E-24Gb_12hi-{a.stacks}stack.yaml")


def write_cfg(a, n, phase):
    name = name_of(a, n, phase)
    stats = f"zsim_stats/barrier/{name}"
    (SIM / "zsim_stats" / "barrier" / "logs").mkdir(parents=True, exist_ok=True)
    channels = a.channels * a.stacks
    cmd = (f"{APP} --participants {n} --rounds {a.rounds} --warmup {a.warmup} --channels {channels} "
           f"--chan-stride {a.stride} --mhz {a.mhz} --map cpu --csv zsim_stats/barrier/{name}.barriers.csv")
    cfg = CFG.format(mhz=int(a.mhz), participants=n, mem=mem_of(a), stats=stats, phase=phase, cmd=cmd)
    path = HERE / "configs" / f"{name}.cfg"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cfg)
    return name, path


def done(name):
    log = SIM / "zsim_stats" / "barrier" / "logs" / f"{name}.log"
    return log.exists() and "BARRIER period_cycles" in log.read_text(errors="replace")


def launch(a, n, phase):
    name, path = write_cfg(a, n, phase)
    log = SIM / "zsim_stats" / "barrier" / "logs" / f"{name}.log"
    if done(name):
        return name, 0, 0.0
    script = (f"cd /pnm/DAMOV/simulator && setarch x86_64 -R ./build/opt/zsim barrier/configs/{name}.cfg "
              f"> zsim_stats/barrier/logs/{name}.log 2>&1; rc=$?; "
              f"chown -R {os.getuid()}:{os.getgid()} zsim_stats barrier; exit $rc")
    cmd = ["docker", "run", "--rm", "--privileged", "-v", f"{ROOT}:/pnm", "-e", "OMP_NUM_THREADS=1", IMAGE,
           "bash", "-c", script]
    t0 = time.time()
    rc = subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    text = log.read_text(errors="replace") if log.exists() else ""
    if rc == 0 and ("BARRIER period_cycles" not in text or "Panic" in text or "VERIFY FAIL" in text):
        rc = 3
    return name, rc, time.time() - t0


NUM = re.compile(r"([a-z_]+)=(-?[0-9]+(?:\.[0-9]+)?)(?![0-9.])")


def summarise(name):
    log = SIM / "zsim_stats" / "barrier" / "logs" / f"{name}.log"
    row = {"run": name}
    text = log.read_text(errors="replace") if log.exists() else ""
    for line in text.splitlines():
        if line.startswith("BARRIER "):
            for k, v in NUM.findall(line):
                row[k] = float(v)
    parts = name.split("__")  # the run name is authoritative for the sweep axes
    row["participants"] = int(parts[1][1:])
    row["phase"] = int(parts[2][1:])
    row["mhz"] = int(parts[3][1:])
    row["stacks"] = int(parts[4][1:]) if len(parts) > 4 else 1
    row["verify"] = "PASS" if "VERIFY PASS" in text else ("FAIL" if "VERIFY FAIL" in text else "")
    row["layout"] = "OK" if " OK" in "".join(l for l in text.splitlines() if l.startswith("BARRIER layout")) else "MISMATCH"
    stats = SIM / "zsim_stats" / "barrier" / f"{name}.ramulator2.stats.yaml"
    if stats.exists():
        body = stats.read_text(errors="replace")
        for key in ("host_requests", "pim_requests", "pim_local_requests", "pim_hops", "host_latency", "pim_latency",
                    "transfers"):
            m = re.search(rf"^\s*{key}:\s*([0-9]+)", body, re.M)
            if m:
                row[key] = int(m.group(1))
    return row


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--participants", type=int)
    ap.add_argument("--sweep", default="")
    ap.add_argument("--phases", default="1000")
    ap.add_argument("--rounds", type=int, default=50)
    ap.add_argument("--warmup", type=int, default=2)
    ap.add_argument("--channels", type=int, default=16, help="channels (PIM units) per stack")
    ap.add_argument("--stacks", type=int, default=1, help="HBM3E stacks; more than 16 PIM units needs more stacks")
    ap.add_argument("--stride", type=int, default=1024)
    ap.add_argument("--mhz", type=float, default=2000)
    ap.add_argument("--mem", default="")
    ap.add_argument("--jobs", type=int, default=4)
    ap.add_argument("--collect", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    points = [int(x) for x in a.sweep.split(",") if x] or ([a.participants] if a.participants else [])
    phases = [int(x) for x in a.phases.split(",")]
    if not points:
        ap.error("need --participants or --sweep")
    combos = list(itertools.product(points, phases))

    if not a.collect:
        todo = [c for c in combos if not done(name_of(a, *c))]
        print(f"{len(combos)} runs, {len(todo)} to do, {a.jobs} in parallel")
        if a.dry_run:
            for n, phase in todo:
                print("  ", write_cfg(a, n, phase)[1])
            return 0
        with ThreadPoolExecutor(a.jobs) as ex:
            for name, rc, wall in ex.map(lambda c: launch(a, *c), todo):
                print(f"rc={rc} wall={wall:.0f}s {name}", flush=True)

    # The summary always covers every finished run, not just this invocation's combos.
    names = sorted(p.stem for p in (SIM / "zsim_stats" / "barrier" / "logs").glob("*.log"))
    rows = [summarise(n) for n in names]
    out = SIM / "zsim_stats" / "barrier" / "summary.csv"
    keys = sorted({k for r in rows for k in r},
                  key=lambda k: (k not in ("run", "participants", "stacks", "phase", "mhz"), k))
    with open(out, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)
    print(f"summary -> {out} ({len(rows)} runs)")
    for r in sorted(rows, key=lambda r: (r["mhz"], r["participants"], r["phase"])):
        if r.get("period_ns"):
            print(f"n={r['participants']:5d} stacks={r['stacks']:3d} phase={r['phase']:6d} f={r['mhz']:5d} period={r['period_ns']:9.1f} ns "
                  f"wait_last={r.get('wait_last_ns', 0):9.1f} wait_first={r.get('wait_first_ns', 0):9.1f} "
                  f"host_polls/barrier={r.get('host_polls_per_barrier')} "
                  f"inv={r.get('ts_inversions')}/{r.get('of')}  {r['verify']} {r['layout']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
