#!/usr/bin/env python3
"""SynCron on DAMOV (HPCA'21 Table 5, HBM variant): config generation and runs.

  run.py --workload probe --threads 64                            # S1 machine model + throughput probe
  run.py --workload barrier --syncron --scheme syncron            # S4/S6 barrier, 15 clients/unit across units
  run.py --workload barrier --syncron --schemes syncron,ideal,central,hier   # S6: the paper's four systems
  run.py --workload barrier --syncron --scope unit --groups 8 --st-list 64,8,4,2   # S5: drive the ST into overflow
  run.py --collect                                                # rebuild summary.csv

Machine (Table 5, HBM): `--units` NDP units x `--cores-per-unit` in-order cores at `--mhz` (2000 per the user's
decision; the paper says 2500), private 16 KB 2-way 4-cycle L1I/L1D, no shared cache and no coherence (the LLC is
present but bypassed, as in DAMOV's PIM template, so it adds no latency and holds no data), a buffered crossbar per
unit via zsim's M/D/1 mesh network, and HBM 1.0 (4 stacks, 4 GB, 500 MHz, 8 channels/stack) through the Ramulator
2.1 fork's HBMStack with `stacks = units`.

`--scheme` picks which of the paper's four systems the run models (Sec 6): `syncron` (the Synchronization Engine),
`ideal` (zero synchronization overhead), `central` (one software server core in the system) and `hier` (one per
unit). The last two coordinate in software on a dedicated NDP core and use only the simulator's message transport,
which is why they need a core per unit: the default 15 clients per unit is the paper's own convention, and every
scheme runs on the same client cores.

Not yet modelled (later phases): the remaining primitives -- locks, semaphores, condition variables (S10) -- and the
paper's workloads (S11).

The config follows DAMOV's own `templates/template_pim_inorder.cfg` in structure (in-order `Timing` cores, private
L1I/L1D, a bypassed LLC standing in for "no shared cache", and the same `sim` block), but it is generated rather than
substituted into, because the template has a single core group and no per-group PIM flag -- four NDP units need four
groups -- and because every cache and clock value Table 5 gives differs from the template's. Deviations from the
template that are deliberate: 2 GHz instead of 2400 (user's decision), 16 KB 2-way 4-cycle L1I and L1D instead of
32 KB (Table 5), `banks = units` on the LLC so the crossbar has a per-unit endpoint, Ramulator2 + HBM1 in `ns` clock
mode instead of Ramulator1 + HMC, per-core `pim` flags instead of the global `sim.pimMode`, and a larger
`statsPhaseInterval` (fewer stats dumps, wall-time only). The LLC's `latency` is irrelevant under `bypass`: init.cpp
zeroes latency, accLat and invLat when a cache is bypassed.
"""
import argparse
import csv
import os
import pathlib
import re
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
SIM = HERE.parent
ROOT = SIM.parent.parent
IMAGE = "zsim-bionic-r2"

CORE_GROUP = """        unit{u} = {{
            type = "{core}";
            cores = {cores};
            icache = "l1i_u{u}";
            dcache = "l1d_u{u}";
            pim = true;
        }};
"""

L1_GROUP = """        l1i_u{u} = {{ caches = {cores}; size = {l1}; latency = {l1lat}; array = {{ type = "SetAssoc"; ways = {ways}; }}; }};
        l1d_u{u} = {{ caches = {cores}; size = {l1}; latency = {l1lat}; array = {{ type = "SetAssoc"; ways = {ways}; }}; }};
"""

CFG = """// Generated by syncron/run.py -- SynCron (HPCA'21) Table 5, HBM variant.
sys = {{
    lineSize = 64;
    frequency = {mhz};

    // Table 5: buffered crossbar per NDP unit, 1-cycle arbitration + 1 cycle/hop, M/D/1 queuing.
{network_block}

    cores = {{
{cores_blocks}    }};

    caches = {{
{l1_blocks}
        // No shared cache and no coherence in an NDP unit (Table 5). The LLC exists only because zsim needs exactly
        // one parentless cache group; `bypass` makes it forward every access to memory with no latency and no data,
        // as DAMOV's own PIM template does. One bank per unit, so the crossbar has a per-unit endpoint.
        llc = {{
            caches = 1;
            banks = {units};
            size = 4194304;
            latency = 0;
            array = {{ type = "SetAssoc"; hash = "H3"; ways = 16; }};
            bypass = true;
            children = "{llc_children}";
        }};
    }};

{syncron_block}
    mem = {{
        type = "Ramulator2";
        clockMode = "ns";
        ramulatorConfig = "{mem}";
        latency = 1;
    }};
}};

sim = {{
    pimMode = false;          // per-core: sys.cores.<group>.pim
    stats = "{stats}";
    phaseLength = {phase};
{instr_cap}
    statsPhaseInterval = 100000;
    printHierarchy = true;
    gmMBytes = 8192;
    pinOptions = "-ifeellucky";
    deadlockDetection = false;
}};

process0 = {{
    command = "{cmd}";
    startFastForwarded = True;
}};
"""

WORKLOADS = {
    # S1 throughput probe: per-thread streaming and pointer chasing, no synchronization.
    # --units/--stack-mb must match the memory config, so each thread's data lands in its own unit's stack.
    "probe": ("../workloads/syncron/probe --threads {threads} --mode {mode} --kb {kb} --iters {iters} "
              "--units {units} --stack-mb {stack_mb}{arena}"),
    # S3 ISA check: req_sync round trips to the local SE.
    "ping": ("../workloads/syncron/ping --threads {threads} --reps {iters} --units {units} "
             "--cores-per-unit {cores_per_unit} --stack-mb {stack_mb}"),
    # S4/S5/S6: the barrier primitive under each scheme. One thread per core; --clients-per-unit decides how many of
    # them are participants and leaves core 0 of each unit for a software server (Central/Hier) or idle.
    "barrier": ("../workloads/syncron/barrier --scheme {scheme} --scope {mode} "
                "--clients-per-unit {clients_per_unit} --units-used {units_used} --groups {groups} "
                "--rounds {iters} --units {units} --cores-per-unit {cores_per_unit} --stack-mb {stack_mb}"),
}

# The Synchronization Engine (Table 5). Only added to the config when --syncron is given.
SYNCRON_BLOCK = """
    syncron = {{
        scheme = "{scheme}";         // syncron | ideal | central | hier (Sec 6)
        units = {units};
        coresPerUnit = {cores_per_unit};
        stEntries = {st_entries};    // Table 5: 64
        indexingCounters = 256;      // Table 5
        spuMHz = 1000;               // Table 5
        serviceCycles = 12;          // Table 5: SPU cycles per message
        localMsgCycles = {local_msg};    // core <-> local SE, one way
        globalMsgCycles = {global_msg};  // local SE <-> Master SE, one way (40 ns)
        bytesPerUnit = {bytes_per_unit}L;
        // Sec 4.4 overflow: one syncronVar access, in core cycles. Measured on this machine model (the S2 chase run
        // reports pim_latency/pim_requests = 29.4 memory ticks = 58.8 ns = 118 core cycles at 2 GHz).
        overflowMemCycles = {overflow_mem};
    }};
"""

NAME_PATTERNS = [
    (re.compile(r"^u(\d+)x(\d+)$"), lambda m, r: r.update(units_x_cores=f"{m.group(1)}x{m.group(2)}")),
    (re.compile(r"^t(\d+)$"), lambda m, r: r.update(threads=int(m.group(1)))),
    (re.compile(r"^c(\d+)x(\d+)$"), lambda m, r: r.update(clients_per_unit=int(m.group(1)),
                                                          units_used=int(m.group(2)))),
    (re.compile(r"^g(\d+)$"), lambda m, r: r.update(groups=int(m.group(1)))),
    (re.compile(r"^st(\d+)$"), lambda m, r: r.update(st_entries=int(m.group(1)))),
    (re.compile(r"^p(\d+)$"), lambda m, r: r.update(phase=int(m.group(1)))),
    (re.compile(r"^f(\d+)$"), lambda m, r: r.update(mhz=int(m.group(1)))),
    (re.compile(r"^(timing|ooo)$"), lambda m, r: r.update(core=m.group(1))),
    (re.compile(r"^(syncron|ideal|central|hier)$"), lambda m, r: r.update(scheme=m.group(1))),
    (re.compile(r"^(nonet|noarena)$"), lambda m, r: r.update(**{m.group(1): 1})),
]

SYNCRON_STATS = ("reqSync", "reqAsync", "barrierPolls", "localMsgs", "globalMsgs", "queueCycles", "serviceCycles",
                 "barriers", "barrierParticipants", "barrierReleaseCycles", "barrierSpanCycles", "barrierSkewCycles",
                 "stPeakEntries", "arrivals", "overflowMsgs", "overflowBarriers", "overflowAliased",
                 "overflowMemAccesses", "overflowMemCycles", "stFullEvents", "indexingCounterPeak", "swMsgs",
                 "swGlobalMsgs", "swMsgsReceived", "swRecvEmpty", "swMsgWaitCycles")


def name_of(a):
    parts = [f"{a.workload}_{a.mode if a.workload in ('probe', 'barrier') else 'se'}"]
    if a.workload == "barrier":
        parts += [a.scheme, f"u{a.units}x{a.cores_per_unit}", f"c{a.clients_per_unit}x{a.units_used}",
                  f"g{a.groups}", f"st{a.st_entries}"]
    else:
        parts += [f"u{a.units}x{a.cores_per_unit}", f"t{a.threads}"]
    parts += [f"p{a.phase}", f"f{int(a.mhz)}", a.core.lower()]
    if a.no_network:
        parts.append("nonet")
    if a.no_arena:
        parts.append("noarena")
    return "__".join(parts)


def write_cfg(a):
    name = name_of(a)
    stats = f"zsim_stats/syncron/{name}"
    (SIM / "zsim_stats" / "syncron" / "logs").mkdir(parents=True, exist_ok=True)
    cores_blocks = "".join(CORE_GROUP.format(u=u, cores=a.cores_per_unit, core=a.core) for u in range(a.units))
    l1_blocks = "".join(L1_GROUP.format(u=u, cores=a.cores_per_unit, l1=a.l1_bytes, l1lat=a.l1_latency, ways=a.l1_ways)
                        for u in range(a.units))
    llc_children = " ".join(f"l1i_u{u}|l1d_u{u}" for u in range(a.units))
    cmd = WORKLOADS[a.workload].format(threads=a.threads, mode=a.mode, kb=a.kb, iters=a.iters, units=a.units,
                                       cores_per_unit=a.cores_per_unit, stack_mb=a.stack_mb, scheme=a.scheme,
                                       clients_per_unit=a.clients_per_unit, units_used=a.units_used,
                                       groups=a.groups, arena=" --no-arena" if a.no_arena else "")
    network_block = ("" if a.no_network else
                     f'    networkType = "mesh";\n    networkFile = "syncron/{a.netfile}";\n')
    # Table 5's 40 ns inter-unit traversal and 1-cycle-arb + 1-cycle-hop crossbar, in core cycles.
    global_msg = int(round(40e-9 * a.mhz * 1e6))
    syncron_block = ("" if not a.syncron else
                     SYNCRON_BLOCK.format(scheme=a.scheme, units=a.units, cores_per_unit=a.cores_per_unit,
                                          local_msg=2, global_msg=global_msg, st_entries=a.st_entries,
                                          overflow_mem=a.overflow_mem_cycles,
                                          bytes_per_unit=a.stack_mb * 1024 * 1024))
    # The template caps runs at 1e9 instructions; keep the knob, because "equal-instruction windows" is the planned
    # mitigation for large inputs (scope S12). maxTotalInstrs counts instructions summed over all cores.
    instr_cap = ("" if not a.max_instrs else
                 f"    maxTotalInstrs = {a.max_instrs}L;\n    maxOffloadInstrs = {a.max_instrs}L;\n")
    cfg = CFG.format(mhz=int(a.mhz), network_block=network_block, instr_cap=instr_cap,
                     syncron_block=syncron_block, cores_blocks=cores_blocks, l1_blocks=l1_blocks,
                     units=a.units, llc_children=llc_children, mem=a.mem, stats=stats, phase=a.phase, cmd=cmd)
    path = HERE / "configs" / f"{name}.cfg"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cfg)
    return name, path


def done(name):
    log = SIM / "zsim_stats" / "syncron" / "logs" / f"{name}.log"
    if not log.exists():
        return False
    text = log.read_text(errors="replace")
    return any(m in text for m in ("PROBE done", "PING done", "BARRIER done"))


def launch(a):
    name, _ = write_cfg(a)
    log = SIM / "zsim_stats" / "syncron" / "logs" / f"{name}.log"
    if done(name) and not a.force:
        return name, 0, 0.0, ""
    script = (f"cd /pnm/DAMOV/simulator && {{ time setarch x86_64 -R ./build/opt/zsim syncron/configs/{name}.cfg "
              f"> zsim_stats/syncron/logs/{name}.log 2>&1 ; }} 2> zsim_stats/syncron/logs/{name}.time; rc=$?; "
              f"chown -R {os.getuid()}:{os.getgid()} zsim_stats syncron; exit $rc")
    cmd = ["docker", "run", "--rm", "--privileged", "-v", f"{ROOT}:/pnm", IMAGE, "bash", "-c", script]
    t0 = time.time()
    rc = subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    text = log.read_text(errors="replace") if log.exists() else ""
    if rc == 0 and (not any(m in text for m in ("PROBE done", "PING done", "BARRIER done")) or "Panic" in text
                    or "Failed assertion" in text or "VERIFY FAIL" in text):
        rc = 3
    return name, rc, time.time() - t0, text


def summarise(name):
    row = {"run": name}
    base = SIM / "zsim_stats" / "syncron"
    log = base / "logs" / f"{name}.log"
    text = log.read_text(errors="replace") if log.exists() else ""
    m = re.search(r"PROBE done threads=(\d+) mode=(\w+) checksum=(\d+)", text)
    if m:
        row.update(threads=int(m.group(1)), mode=m.group(2))
    m = re.search(r"PING threads=(\d+) reps=(\d+) median_cycles=([\d.]+) min_cycles=(\d+) max_cycles=(\d+)", text)
    if m:
        row.update(threads=int(m.group(1)), ping_median=float(m.group(3)), ping_min=int(m.group(4)),
                   ping_max=int(m.group(5)))
    for line in text.splitlines():
        if line.startswith("BARRIER ") and "=" in line:
            for tok in line.split()[1:]:
                if tok.count("=") == 1:
                    k, v = tok.split("=")
                    try:
                        row[k] = float(v)
                    except ValueError:
                        row[k] = v
    if "VERIFY PASS" in text:
        row["verify"] = "PASS"
    elif "VERIFY FAIL" in text:
        row["verify"] = "FAIL"
    tf = base / "logs" / f"{name}.time"
    if tf.exists():
        for k, mm, ss in re.findall(r"(real|user|sys)\s+(\d+)m([\d.]+)s", tf.read_text()):
            row[k] = round(int(mm) * 60 + float(ss), 1)
        if row.get("real"):
            row["cpu_used"] = round((row.get("user", 0) + row.get("sys", 0)) / row["real"], 2)
    stats = base / f"{name}.zsim.out"
    if stats.exists():
        d = [x for x in stats.read_text().split("===") if x.strip()][-1]
        row["instrs"] = sum(int(x) for x in re.findall(r"^\s+instrs: (\d+)", d, re.M))
        cycles = [int(x) for x in re.findall(r"^\s+cycles: (\d+)", d, re.M)]
        row["max_core_cycles"] = max(cycles) if cycles else 0
        m = re.search(r"^ phase: (\d+)", d, re.M)
        row["phases"] = int(m.group(1)) if m else 0
        m = re.search(r"^\s+memTicks: (\d+)", d, re.M)
        row["mem_ticks"] = int(m.group(1)) if m else 0
        if row.get("real"):
            row["instr_per_s"] = int(row["instrs"] / row["real"])
            row["cycles_per_s"] = int(row["max_core_cycles"] / row["real"])
        # The engine's own stats: everything the SE charged, including the exact modelled barrier cost.
        block = re.search(r"^ syncron:.*?(?=^ \S)", d, re.M | re.S)
        if block:
            for key in SYNCRON_STATS:
                mm = re.search(rf"^\s+{key}: (\d+)", block.group(0), re.M)
                if mm:
                    row[key] = int(mm.group(1))
            if row.get("barriers"):
                row["modelled_release_cycles"] = round(row["barrierReleaseCycles"] / row["barriers"], 1)
            if row.get("arrivals"):
                row["overflow_pct"] = round(100.0 * row.get("overflowMsgs", 0) / row["arrivals"], 2)
    r2 = base / f"{name}.ramulator2.stats.yaml"
    if r2.exists():
        body = r2.read_text(errors="replace")
        for key in ("host_requests", "pim_requests", "pim_local_requests", "pim_remote_stack_requests",
                    "rejected_ingress_full", "pim_latency", "transfers", "inter_unit_bytes",
                    "inter_unit_queue_ticks"):
            m = re.search(rf"^\s*{key}:\s*([0-9]+)", body, re.M)
            if m:
                row[key] = int(m.group(1))
    for part in name.split("__")[1:]:
        for pat, apply in NAME_PATTERNS:
            m = pat.match(part)
            if m:
                apply(m, row)
                break
    return row


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workload", default="probe", choices=sorted(WORKLOADS))
    ap.add_argument("--units", type=int, default=4)
    ap.add_argument("--cores-per-unit", type=int, default=16)
    ap.add_argument("--threads", type=int, default=64, help="probe/ping only; barrier uses --clients-per-unit")
    ap.add_argument("--core", default="Timing", choices=["Timing", "OOO"], help="Timing = in-order (Table 5)")
    ap.add_argument("--mhz", type=float, default=2000)
    ap.add_argument("--l1-bytes", type=int, default=16384)
    ap.add_argument("--l1-ways", type=int, default=2)
    ap.add_argument("--l1-latency", type=int, default=4)
    ap.add_argument("--phase", type=int, default=1000)
    ap.add_argument("--phases", default="", help="comma-separated phase lengths to sweep")
    ap.add_argument("--mode", default="stream", choices=["stream", "chase", "unit", "units"],
                    help="probe: stream|chase; barrier: unit|units (the barrier's scope)")
    ap.add_argument("--kb", type=int, default=256, help="per-thread working set")
    ap.add_argument("--iters", type=int, default=20, help="probe iterations / ping reps / barrier rounds")
    ap.add_argument("--stack-mb", type=int, default=1024, help="modelled memory per stack; must match the memory config")
    ap.add_argument("--no-arena", action="store_true", help="malloc instead of per-unit placement (the S1 baseline)")
    ap.add_argument("--mem", default="ramulator2-configs/HBM1-1Gb-4stack.yaml")
    ap.add_argument("--netfile", default="network_4x16.mesh")
    ap.add_argument("--no-network", action="store_true", help="drop the crossbar model (sanity check only)")
    ap.add_argument("--syncron", action="store_true", help="add the Synchronization Engine (sys.syncron)")
    ap.add_argument("--scheme", default="syncron", choices=["syncron", "ideal", "central", "hier"],
                    help="which of the paper's four systems to model (Sec 6)")
    ap.add_argument("--schemes", default="", help="comma-separated schemes to sweep")
    ap.add_argument("--clients-per-unit", type=int, default=15,
                    help="participants per NDP unit; 15 is the paper's convention (one core per unit is left for a "
                         "software server), 16 is SynCron's own design point")
    ap.add_argument("--units-used", type=int, default=4, help="how many NDP units hold participants")
    ap.add_argument("--groups", type=int, default=1,
                    help="independent barriers at once: per unit for --mode unit, in total for --mode units")
    ap.add_argument("--st-entries", type=int, default=64, help="Synchronization Table entries (Table 5: 64)")
    ap.add_argument("--st-list", default="", help="comma-separated ST sizes to sweep (the overflow experiment)")
    ap.add_argument("--overflow-mem-cycles", type=int, default=118,
                    help="core cycles for one syncronVar access by a Master SE in overflow mode")
    ap.add_argument("--max-instrs", type=int, default=0,
                    help="cap the run at this many instructions summed over all cores (0 = no cap); the equal-"
                         "instruction-window mitigation for large inputs")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--collect", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    if not a.collect:
        phases = [int(x) for x in a.phases.split(",")] if a.phases else [a.phase]
        schemes = [x for x in a.schemes.split(",")] if a.schemes else [a.scheme]
        sts = [int(x) for x in a.st_list.split(",")] if a.st_list else [a.st_entries]
        for phase in phases:
            for scheme in schemes:
                for st in sts:
                    a.phase, a.scheme, a.st_entries = phase, scheme, st
                    if a.dry_run:
                        print(write_cfg(a)[1])
                        continue
                    name, rc, wall, _ = launch(a)
                    print(f"rc={rc} wall={wall:.0f}s {name}", flush=True)

    names = sorted(p.stem for p in (SIM / "zsim_stats" / "syncron" / "logs").glob("*.log"))
    rows = [summarise(n) for n in names]
    if rows:
        out = SIM / "zsim_stats" / "syncron" / "summary.csv"
        keys = sorted({k for r in rows for k in r}, key=lambda k: (k not in ("run", "scheme", "units_x_cores",
                                                                            "threads", "phase", "core"), k))
        with open(out, "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=keys)
            w.writeheader()
            w.writerows(rows)
        print(f"summary -> {out}")
        for r in rows:
            if r.get("period_cycles"):
                print(f"{r['run'][:62]:<62} period={r['period_cycles']:>9.1f} wait_last={r.get('wait_last_cycles', 0):>8.1f} "
                      f"modelled={r.get('modelled_release_cycles', float('nan')):>8.1f} "
                      f"overflow={r.get('overflow_pct', 0):>5.1f}% real={r.get('real', 0):6.1f}s")
            elif r.get("instr_per_s"):
                pim = r.get("pim_requests") or 0
                loc = (r.get("pim_local_requests") or 0) / pim * 100 if pim else 0
                rem = (r.get("pim_remote_stack_requests") or 0) / pim * 100 if pim else 0
                print(f"{r['run'][:62]:<62} real={r.get('real', 0):7.1f}s cpu={r.get('cpu_used', 0):5.2f}x "
                      f"instr/s={r['instr_per_s']:>9,} cycles/s={r['cycles_per_s']:>8,} "
                      f"local={loc:5.1f}% remote={rem:5.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
