#!/usr/bin/env python3
"""CPU baseline for the barrier study: a zsim multicore / multi-processor host, no PIM anywhere.

  run.py --threads 1,2,4,8,16,32,64,128,256,512,1024 --nets 1us,40ns [--jobs 4]
  run.py --table                                    # print the results table from the finished runs

Machine: `--cores-per-proc` (64) Westmere-class OOO cores per processor at 2 GHz; private 16 KB L1I (4-way, 3 cycles)
and 16 KB L1D (8-way, 4 cycles), private 256 KB L2 (8-way, 7 cycles); one 4 MB 16-way L3 per processor (Timing,
16 banks, 27 cycles) shared by that processor's cores and coherent across them (zsim's MESI directories), none shared
between processors; HBM3E main memory: one 24Gb 12-hi stack (36 GiB, 16 channels at 9.6 Gbps) through Ramulator 2.1's
HBMStack model on its host path only -- a plain memory device behind the controller, no PIM request ever issued
(GenericDRAM cannot take HBM3E: its address mappers need power-of-two row and SID counts, HBM3E's 24 Gb die has
neither).
Latencies are the ones DAMOV's Westmere host template uses; only the sizes are the study's.

The L3 is one zsim cache group with one cache per processor: zsim wires a group's caches to consecutive equal shares
of the children, so cache p serves the L2s of cores 64p .. 64p+63. (zsim allows one last-level group; init.cpp now
connects every cache of it to memory, not only the first.)

Beyond one processor the program is a hybrid MPI job, one rank per processor, and the processors talk over the
cluster network of src/cluster_net.h. `--nets` picks its numbers:
  1us   1 us end to end per message (MPI send overhead + wire + switch + MPI receive overhead), 12.5 GB/s ports
        (100 Gb/s), 64 B per message (a zero-byte MPI message's header). The range of small-message MPI latency on a
        100 Gb/s-class cluster fabric; no fabric protocol (flow control, packets, routing) is modelled.
  800g  as 1us, with 800 Gb/s (100 GB/s) ports -- today's fastest Ethernet / InfiniBand port speed
  40ns  SynCron's inter-unit link numbers (HPCA'21 Table 5): 40 ns, 12.8 GB/s, 18 B
  zero  a control: messages free and instant -- what is left is the program and zsim's phase granularity
"""
import argparse
import os
import pathlib
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor

HERE = pathlib.Path(__file__).resolve().parent
SIM = HERE.parent
ROOT = SIM.parent.parent
IMAGE = "zsim-bionic-r2"
OUT = SIM / "zsim_stats" / "cpu-barrier"

NETS = {
    "1us": dict(latency_ns=1000.0, bw_gbps=12.5, msg_bytes=64),
    "40ns": dict(latency_ns=40.0, bw_gbps=12.8, msg_bytes=18),
    "800g": dict(latency_ns=1000.0, bw_gbps=100.0, msg_bytes=64),
    "zero": dict(latency_ns=0.0, bw_gbps=0.0, msg_bytes=0),
}

CFG = """// Generated by cpu-barrier/run.py -- CPU baseline: {procs} processor(s) x {cpp} Westmere-class cores, hybrid MPI.
sys = {{
    lineSize = 64;
    frequency = {mhz};

    cores = {{
        core = {{
            type = "OOO";
            cores = {threads};
            icache = "l1i";
            dcache = "l1d";
        }};
    }};

    caches = {{
        l1i = {{ caches = {threads}; size = 16384; latency = 3; array = {{ type = "SetAssoc"; ways = 4; }}; }};
        l1d = {{ caches = {threads}; size = 16384; latency = 4; array = {{ type = "SetAssoc"; ways = 8; }}; }};
        l2 = {{
            caches = {threads};
            size = 262144;
            latency = 7;
            array = {{ type = "SetAssoc"; ways = 8; }};
            children = "l1i|l1d";
        }};
        // One 4 MB L3 per processor: cache p serves the L2s of cores {cpp}p .. {cpp}p+{cpp_1}.
        l3 = {{
            type = "Timing";
            caches = {procs};
            banks = 16;
            size = 4194304;
            latency = 27;
            // Blocking directory (coherence_ctrls.h): a line moves between cores one transfer at a time, each paying
            // its full latency -- zsim otherwise lets N contending cores each take the line at once.
            serializeTransfers = true;
            array = {{ type = "SetAssoc"; hash = "H3"; ways = 16; }};
            children = "l2";
        }};
    }};
{cluster}
    mem = {{
        type = "Ramulator2";
        clockMode = "ns";
        ramulatorConfig = "{mem}";
        latency = 1;
    }};
}};

sim = {{
    pimMode = false;
    stats = "{stats}";
    phaseLength = {phase};
    statsPhaseInterval = 100000;
    printHierarchy = false;
    gmMBytes = {gm};
    pinOptions = "-ifeellucky";
    deadlockDetection = false;
}};

process0 = {{
    command = "{cmd}";
    startFastForwarded = True;
}};
"""

CLUSTER = """
    // Network between the processors (src/cluster_net.h): single switch, one NIC port per processor.
    cluster = {{
        nodes = {procs};
        coresPerNode = {cpp};
        latencyNs = {latency_ns};    // end to end, MPI software overhead included
        bwGBps = {bw_gbps};          // per NIC port
        msgBytes = {msg_bytes};
    }};
"""


def name_of(a, threads, net):
    procs = max(1, -(-threads // a.cores_per_proc))
    parts = [f"cpubar_t{threads}", f"cpp{a.cores_per_proc}", f"n{net}" if procs > 1 else "nlocal",
             f"w{a.warmup}", f"r{a.rounds}", f"p{a.phase}"]
    if a.barrier != "central":  # the centralized barrier keeps its original run names
        parts.insert(1, f"b{a.barrier}")
    if a.check:
        parts.append("check")
    return "__".join(parts)


def write_cfg(a, threads, net):
    procs = max(1, -(-threads // a.cores_per_proc))
    name = name_of(a, threads, net)
    cluster = "" if procs == 1 else CLUSTER.format(procs=procs, cpp=a.cores_per_proc, **NETS[net])
    cmd = (f"../workloads/cpu-barrier/cpu_barrier --threads {threads} --cores-per-proc {a.cores_per_proc} "
           f"--rounds {a.rounds} --warmup {a.warmup} --barrier {a.barrier}" + (" --check" if a.check else ""))
    cfg = CFG.format(procs=procs, cpp=a.cores_per_proc, cpp_1=a.cores_per_proc - 1, mhz=int(a.mhz), threads=threads,
                     cluster=cluster, mem=a.mem, stats=f"zsim_stats/cpu-barrier/{name}", phase=a.phase,
                     gm=a.gm_mb, cmd=cmd)
    path = HERE / "configs" / f"{name}.cfg"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cfg)
    return name


def finished(name):
    log = OUT / "logs" / f"{name}.log"
    return log.exists() and "CPUBAR done" in log.read_text(errors="replace")


def launch(a, threads, net):
    name = write_cfg(a, threads, net)
    (OUT / "logs").mkdir(parents=True, exist_ok=True)
    if finished(name) and not a.force:
        return name, 0, 0.0
    script = (f"cd /pnm/DAMOV/simulator && {{ time setarch x86_64 -R ./build/opt/zsim cpu-barrier/configs/{name}.cfg "
              f"> zsim_stats/cpu-barrier/logs/{name}.log 2>&1 ; }} 2> zsim_stats/cpu-barrier/logs/{name}.time; "
              f"rc=$?; chown -R {os.getuid()}:{os.getgid()} zsim_stats cpu-barrier; exit $rc")
    t0 = time.time()
    rc = subprocess.call(["docker", "run", "--rm", "--privileged", "-v", f"{ROOT}:/pnm", IMAGE, "bash", "-c", script],
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    text = (OUT / "logs" / f"{name}.log").read_text(errors="replace")
    if rc == 0 and ("CPUBAR done" not in text or "VERIFY FAIL" in text or "Panic" in text):
        rc = 3
    return name, rc, time.time() - t0


def load(name):
    log = OUT / "logs" / f"{name}.log"
    if not log.exists():
        return None
    text = log.read_text(errors="replace")
    r = {"name": name, "ok": "CPUBAR done" in text and "VERIFY PASS" in text}
    for k, v in re.findall(r"\b(\w+_cycles|period_min|period_max|threads|procs)=([\d.]+)", text):
        r[k] = float(v)
    tf = OUT / "logs" / f"{name}.time"
    m = re.search(r"real\s+(\d+)m([\d.]+)s", tf.read_text()) if tf.exists() else None
    r["wall"] = int(m.group(1)) * 60 + float(m.group(2)) if m else 0
    st = OUT / f"{name}.zsim.out"
    if st.exists():
        d = [x for x in st.read_text().split("===") if x.strip()][-1]
        b = re.search(r"^ cluster:.*?(?=^ \S)", d, re.M | re.S)
        if b:
            for k in ("msgs", "portQueueCycles", "recvEmpty", "waitCycles"):
                mm = re.search(rf"^\s+{k}: (\d+)", b.group(0), re.M)
                if mm:
                    r[k] = int(mm.group(1))
    return r


def table(a):
    rows = []
    for p in sorted((OUT / "logs").glob("cpubar_*.log")):
        if p.stem.endswith(("__check", "__p10")) or "__trace" in p.stem:
            continue
        r = load(p.stem)
        if r:
            m = re.match(r"cpubar_t(\d+)(?:__b(\w+?))?__cpp\d+__n(\w+?)__", r["name"])
            r["t"], r["barrier"], r["net"] = int(m.group(1)), m.group(2) or "central", m.group(3)
            rows.append(r)
    rows.sort(key=lambda r: (r["barrier"], r["net"] != "local", r["net"], r["t"]))
    print("| barrier | threads | procs | network | period (cyc) | period (ns) | thread barrier 1 | MPI_Barrier | thread barrier 2 "
          "| msgs | port queue | ok | wall |")
    print("|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|:--:|---:|")
    for r in rows:
        if "period_cycles" not in r:
            print(f"| {r['barrier']} | {r['t']} | | {r['net']} | **no result** | | | | | | | {'✓' if r['ok'] else '✗'} | |")
            continue
        sp = lambda k: f"{r[k]:,.0f}" if k in r else "—"
        print(f"| {r['barrier']} | {r['t']} | {int(r.get('procs', 1))} | {r['net']} | {r['period_cycles']:,.0f} | "
              f"{r['period_cycles'] / a.mhz * 1000:,.0f} | {sp('split_intra1_cycles')} | {sp('split_mpi_cycles')} | "
              f"{sp('split_intra2_cycles')} | {r.get('msgs', '—')} | {r.get('portQueueCycles', '—')} | "
              f"{'✓' if r['ok'] else '✗'} | {r['wall']:.0f}s |")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--threads", default="1,2,4,8,16,32,64,128,256,512,1024")
    ap.add_argument("--nets", default="1us,40ns")
    ap.add_argument("--cores-per-proc", type=int, default=64)
    ap.add_argument("--rounds", type=int, default=20)
    ap.add_argument("--warmup", type=int, default=50)
    ap.add_argument("--phase", type=int, default=100)
    ap.add_argument("--mhz", type=float, default=2000)
    ap.add_argument("--mem", default="ramulator2-configs/HBM3E-24Gb_12hi.yaml")
    ap.add_argument("--gm-mb", type=int, default=16384)
    ap.add_argument("--barrier", default="central", choices=["central", "tree"],
                    help="central: sense-reversing counter + thread barrier / MPI / thread barrier; tree: MCS tree, "
                         "root-only MPI between arrival and wake-up")
    ap.add_argument("--check", action="store_true", help="functional check (adds an atomic per arrival)")
    ap.add_argument("--jobs", type=int, default=2)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--table", action="store_true")
    a = ap.parse_args()
    if a.table:
        return table(a)
    todo = []
    for t in (int(x) for x in a.threads.split(",")):
        nets = a.nets.split(",") if t > a.cores_per_proc else ["local"]
        todo += [(t, n) for n in nets]
    with ThreadPoolExecutor(a.jobs) as ex:
        for name, rc, wall in ex.map(lambda tn: launch(a, *tn), todo):
            print(f"{name}: rc={rc} {wall:.0f}s", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
